namespace LibraryAPI.BusinessLogic.DTOs
{
    public enum GenreDTO
    { 
        Fantasy,
        Adventure,
        Romance,
        Contemporary,
        Dystopian,
        Mystery,
        Horror,
        Thriller,
        Paranormal,
        Historicalfiction,
        ScienceFiction,
        Memoir,
        Cooking,
        Art,
        SelfhelpOrPersonal,
        Development,
        Motivational,
        Health,
        History,
        Travel,
        GuideOrHowto,
        FamiliesAndRelationships,
        Humor,
        Childrens,
    }
}
